### ISSUE TITLE
`fp` results in `unknown option: --scheme=path`

### ISSUE THREAD

**Issue by mcmikemn** [thingsiplay/findpick#1]
This is probably user-error and not an issue with your code, but I just installed `fp` (and `fzf`) and when I run `fp` I get "unknown option: --scheme=path". I can run `fp -M` and it works fine. 

I'm running Ubuntu 22.04.04, `fzf` 0.29, `fp` 0.6.

**Comment by thingsiplay** [comment]
`--scheme=path` is an option used by `fzf`, and your version of it is too old. That's why it works with `fp -M`, as this command means to not use menu program. `--scheme=path` got introduced to `fzf` in [v0.33](https://github.com/junegunn/fzf/commit/6fb41a202a97ad3f2437f6e5aee8890268560412) and its current at v0.52.

The problem is, that there are even more changes and additions to it, and my complex script relies on these features. So therefore at the moment I don't want to attempt making it compatible with an old version. But this is unfortunate, because Ubuntu 22.04 isn't that old.

So an option for you would be to download the current version of `fzf` from their official repository at https://github.com/junegunn/fzf/releases or directly [fzf-0.52.1-linux_amd64.tar.gz](https://github.com/junegunn/fzf/releases/download/0.52.1/fzf-0.52.1-linux_amd64.tar.gz) . Then you can use `fp -m /path/to/your/fzf` to point to this downloaded new version of fzf. An alias could help you out even further.


Apology if this is a bit convoluted, but it's the incompatibility with older version.

**Comment by thingsiplay** [comment]
`--scheme=path` is an option used by fzf. Your version is a bit too old, as my script relies on newer functionalities. There are couple of more features that are not supported with older version.

### Set custom menu command

Try a custom menu command with `-m` to only use options that are supported. Here is a suggestion: 

```bash
fp -m 'fzf --reverse --multi --cycle --bind change:first --bind esc:cancel+clear-selection --height=80% --border=none --prompt=$_ --marker=*'
```

Or just as a suggestion, add an alias to your .bashrc:

```bash
alias fpp="fp -m 'fzf --reverse --multi --cycle --bind change:first --bind esc:cancel+clear-selection --height=80% --border=none --prompt=$_ --marker=*'"
```

### Or download newer fzf

But this does not guarantee to work perfectly, as I don't know exactly how all other elements in the script itself would be compatible with older fzf version. An alternative approach would be to download newest version of fzf itself and use that instead.

Official repository at https://github.com/junegunn/fzf/releases or directly [fzf-0.52.1-linux_amd64.tar.gz](https://github.com/junegunn/fzf/releases/download/0.52.1/fzf-0.52.1-linux_amd64.tar.gz) . Then you can use a similar alias like above, but with all options in use as (notice this below alias has more options than the above one, as we use it with the new version of fzf that supports all options):

```bash
alias fpp="fp -m '/path/to/your/new/fzf --reverse --multi --cycle --scheme=path --bind change:first --bind esc:cancel+clear-selection --height=~80% --border=none --prompt=$_ --marker=* --no-separator'"
```

Apology if this is a bit convoluted, but it's the incompatibility with older version.

**Comment by mcmikemn** [comment]
Thanks! I'll DL the newest `fzf`.

**Comment by thingsiplay** [comment]
I think Ubuntu automatically includes `~/bin` directory, so all you would need is to put `fzf` in that directory. Then you don't need any alias for `fp`, as the newest version will be used. Just reopen if this does not work, otherwise I assume it works for you. Have a good day.
